#!/usr/bin/env bash
#a Bash script that displays Best School 10 times except on the 4th line where it displays bad luck and the 8th line where it displays good luck.

i=1

while [ $i -le 10 ]
do 
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
